function embed_file(file, target)
    local file_path = path.join(os.projectdir(), file)
    local file_h_path = path.join(os.projectdir(), string.format("src/private/micro/gen/%s.h", path.basename(file)))

    if os.mtime(file_h_path) >= os.mtime(file_path) then
        return
    end

    local rel_file_path = path.relative(file_path, os.projectdir())
    local rel_file_h_path = path.relative(file_h_path, os.projectdir())

    -- match xmake build format
    cprint("${bright green}[  0%%]: ${bright magenta}<%s>${clear} embedding.file %s -> %s", target:name(), rel_file_path, rel_file_h_path)

    local file_data = io.readfile(file_path)
    local h_file_data = string.format([[
#pragma once

// This file is auto-generated by embed_file.lua. Do not edit manually.
// View the original file at %s for the source content and scripts/embed_file.lua for the generation logic.

namespace micro::gen
{
    const char *%s = R"(%s)";
}
]], file, path.basename(file), file_data)

    io.writefile(file_h_path, h_file_data)
end

return {
    embed_file = embed_file
}