function embed_file(file)
    local file_path = path.join(os.projectdir(), file)
    local file_h_path = path.join(os.projectdir(), string.format("src/private/gen/%s.h", path.basename(file)))

    print(string.format("Embedding file: %s -> %s", file_path, file_h_path))

    local file_data = io.readfile(file_path)
    local h_file_data = string.format([[
#pragma once

// This file is auto-generated by embed_file.lua. Do not edit manually.
// View the original file at %s for the source content and scripts/embed_file.lua for the generation logic.

namespace micro::gen
{
    const char *%s = R"(%s)";
}
]], file, path.basename(file), file_data)

    io.writefile(file_h_path, h_file_data)
end

return {
    embed_file = embed_file
}